### PR TITLE
Mostly complete functionality

### PR DESCRIPTION
**Pull request by sfllaw**
I've gotten Sphinx-HTTP-domain to mostly complete functionality:

Now there are field lists for http:method:: which should make documenting APIs easier.

README has been converted to ReST and setup.py is configured to put that in the PyPi page.

There is http:response:: which should make documenting JSON, XML, etc responses easier.

And you can also use :http:method:`label-name` and :http:response:`label-name` to reference a method or response that you've defined.

Plus, the index is now auto-populated with these items.

### CODE REVIEW

**Comment by deceze** [comment]
Very sorry for the late response. I was trying out your changes and unfortunately got this:

```
Exception occurred:
  File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line 109, in HTTPMethod
    can_collapse=True),
TypeError: __init__() got an unexpected keyword argument 'can_collapse'
```

Traceback:

```
# Sphinx version: 1.0.5
# Python version: 2.6.1
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/cmdline.py", line 172, in main
    warningiserror, tags)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/application.py", line 116, in __init__
    self.setup_extension(extension)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/application.py", line 250, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File ".../Sphinx-HTTP-domain/sphinx_http_domain/__init__.py", line 21, in <module>
    from sphinx_http_domain.directives import HTTPMethod, HTTPResponse
  File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line 93, in <module>
    class HTTPMethod(HTTPDescription):
  File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line 109, in HTTPMethod
    can_collapse=True),
TypeError: __init__() got an unexpected keyword argument 'can_collapse'
```

**Comment by sfllaw** [comment]
Hi there,

Hmm, it looks like this was because TypeField's signature changed in 1.0.6,
to fix a bug:

https://bitbucket.org/birkenfeld/sphinx/changeset/af69933b1f90

I think the best thing to do is to make Sphinx-HTTP-domain require
Sphinx>=1.0.6. Do you agree?

On Thu, Mar 24, 2011 at 5:22 AM, deceze <
reply@reply.github.com>wrote:

> Very sorry for the late response. I was trying out your changes and
> unfortunately got this:
> 
>    Exception occurred:
>      File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line
> 109, in HTTPMethod
>        can_collapse=True),
>    TypeError: **init**() got an unexpected keyword argument 'can_collapse'
> 
> Traceback:
> 
>    # Sphinx version: 1.0.5
>    # Python version: 2.6.1
>    # Docutils version: 0.7 release
>    # Jinja2 version: 2.5.5
>    Traceback (most recent call last):
>      File
> "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/cmdline.py",
> line 172, in main
>        warningiserror, tags)
>      File
> "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/application.py",
> line 116, in **init**
>        self.setup_extension(extension)
>      File
> "/Library/Python/2.6/site-packages/Sphinx-1.0.5-py2.6.egg/sphinx/application.py",
> line 250, in setup_extension
>        mod = **import**(extension, None, None, ['setup'])
>      File ".../Sphinx-HTTP-domain/sphinx_http_domain/**init**.py", line 21,
> in <module>
>        from sphinx_http_domain.directives import HTTPMethod, HTTPResponse
>      File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line
> 93, in <module>
>        class HTTPMethod(HTTPDescription):
>      File ".../Sphinx-HTTP-domain/sphinx_http_domain/directives.py", line
> 109, in HTTPMethod
>        can_collapse=True),
>    TypeError: **init**() got an unexpected keyword argument 'can_collapse'
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/deceze/Sphinx-HTTP-domain/pull/8#issuecomment-911608

## 

Cheers,
Simon - http://ca.linkedin.com/in/sfllaw/

**Comment by deceze** [comment]
Sounds good, didn't realize my Sphinx was that outdated.
Added a note in the Readme for now.

**Comment by sfllaw** [comment]
We should probably change setup.py so it demands the right version of
Sphinx. I tested on 1.0.7.

If you don't do that tonight, I'll commit the change tomorrow.
On Mar 24, 2011 9:48 PM, "deceze" <
reply@reply.github.com>
wrote:

**Pull request merged**
